# DrupalVM configuration for a VirtualBox containing both the "front stage" and
# the "back stage" for www.foia.gov, tailored for local DOJ development.
vagrant_box: geerlingguy/ubuntu1604

# This IP is tweaked because we need it to end with 33.x.
vagrant_ip: 192.168.33.83

# Use only inside-VM workflow - no synced folders, because of restrictive DOJ
# networks/laptops.
vagrant_synced_folders: []
vagrant_synced_folder_default_type: ""

# To deal with Composer's heavy memory usage, provide plenty of RAM.
php_memory_limit: "2048M"
vagrant_memory: 4096

# Apache VirtualHosts - just one each for the front/back stages, plus Adminer.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local-www.foia.doj.gov"
    documentroot: "/var/www/foia.gov/_site"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local-www.foia.doj.gov"
    documentroot: "/var/www/foia.gov/_site"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# The front stage requires node 8.x.
nodejs_version: "8.x"

# We're doing all post-provisioning manually because of restrictive laptops.
post_provision_scripts: []

# Since we work inside the VM, install ubuntu-desktop.
extra_packages:
  - ubuntu-desktop

# XDebug configuration.
# Uncomment the following lines to turn on debugging in the VM.
#php_xdebug_default_enable: 1
#php_xdebug_coverage_enable: 1
#php_xdebug_remote_autostart: 1
#php_xdebug_remote_port: 9200
#php_xdebug_remote_host: localhost
